name: onepan
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.3
  json_annotation: ^4.9.0
  get_it: ^7.6.7
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^3.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/ingredient_catalog.json
    - assets/ingredients/
    - assets/recipes.json
    - assets/images/recipes/
    - assets/images/ingredients/

